# -*- coding: utf-8 -*-
"""CP2-DataScieceKayque.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19EQRUrlx4dTT2aFb368CwhHnxijLUMTS
"""

"""
Nome: Kayque Carvalho da Silva
RM: 561189
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/sample_data/scouts_2015.csv')

print("Dimensões da base", df.shape)
df.head(20)




"""
1) a) Como está estruturado o dataset?
R: O dataset está estruturado em 29.720 linhas e 34 colunas.

b) Quantos jogadores e rodadas temos registrados?
R: Número de jogadores únicos registrados: 1022
R: Número de rodadas únicas registradas: 36

C) Quais variáveis são categóricas e quais são numéricas?
R: Temos 30 numéricas e 4 categóricas.
Numéricas: atleta_id, rodada_id, ano, clube_id, posicao_id, jogos_num, pontos_num, media_num, preco_num_anterior, preco_num, variacao_num, FS, PE, FT, FF, DD, FD, I, PP, RB, FC, GC, CA, CV, SG, DE, GS, status_id.
Categóricas: nome, clube, posicao, status.
"""

num_jogadores = df['atleta_id'].nunique()
num_rodadas = df['rodada_id'].nunique()
print(f"Número de jogadores únicos registrados: {num_jogadores}")
print(f"Número de rodadas únicas registradas: {num_rodadas}")

print("Informações do Dataset:")
info = df.info()

display(df.sample(5, random_state=42))
display(df.describe(include='all').transpose())

#%%
"""

2. Tendência Central (Média, Mediana, Moda)
a) Qual é a pontuação média dos jogadores em uma rodada?
R: A pontuação média dos jogadores em uma rodada é de: 0.95 pontos

b) Qual posição tem a maior mediana de pontos?
R: A posição maior é tec com 2.88 pontos

c) Existe um jogador que aparece como “moda” em gols ou assistências (ou seja, que repete muito em valores)?
R: Foi Ricardo Oliveira com mais gols e Luan 10 com assistencia

"""

media_pontuacao = df['pontos_num'].mean()
print(f"Média: {media_pontuacao:.2f} pontos")

mediana_por_posicao = df.groupby('posicao')['pontos_num'].median().sort_values(ascending=False)
maior_mediana = mediana_por_posicao.index[0]
print("Mediana de pontos por posição:")
print(mediana_por_posicao)
print(f"\nMaior mediana: {maior_mediana} : {mediana_por_posicao.iloc[0]:.2f} pontos")


moda_gols_geral = df['G'].mode()[0]
print(f"Gols mais frequente: {moda_gols_geral}")

df_gols = df[df['G'] > 0]
jogador_mais_gols = df_gols.groupby('apelido')['G'].count().sort_values(ascending=False).head(1)
print(f"\nO jogador que mais vezes apareceu com pelo menos gol:\n{jogador_mais_gols}")

moda_assist_geral = df['A'].mode()[0]
print(f"\nO valor de Assistências mais frequente em toda a base (moda) é: {moda_assist_geral}")

df_assist = df[df['A'] > 0]
jogador_mais_assist = df_assist.groupby('apelido')['A'].count().sort_values(ascending=False).head(1)
print(f"\nO jogador com mais assistencia por jogo:\n{jogador_mais_assist}")


#%%
"""
3. Dispersão (Variância, Desvio Padrão)
a) A pontuação dos atacantes é mais dispersa que a dos zagueiros?
R: Zagueiros: 2.64
R: Atacantes: 3.12
R: A pontuação dos atacantes é maior que a dos zagueiros

b) Qual posição tem maior consistência de desempenho (menor desvio-padrão de pontos)?
R: A posição com maior menor desvio padrão e maior consistencia é: tec (2.20)

c) Como é a variabilidade no preço dos jogadores por posição?
R:  gol    6.076104
    ata    5.491849
    mei    4.591504
    lat    4.422924
    zag    4.384655
    tec    2.862776

"""

desvio_atacante = df[df['posicao'] == 'ata']['pontos_num'].std()
desvio_zagueiro = df[df['posicao'] == 'zag']['pontos_num'].std()

print(f"Desvio padrão para atacantes: {desvio_atacante:.2f}")
print(f"Desvio padrão para zagueiros: {desvio_zagueiro:.2f}\n")


desvio_por_posicao = df.groupby('posicao')['pontos_num'].std().sort_values(ascending=True)
posicao_mais_consistente = desvio_por_posicao.index[0]
print("Desvio Padrão por posição")
print(desvio_por_posicao)
print(f"\nMenor desvio padrão e mais consistente: {posicao_mais_consistente} : {desvio_por_posicao.iloc[0]:.2f}\n")


variabilidade_preco = df.groupby('posicao')['preco_num'].std().sort_values(ascending=False)
print("Variabilidade/DeSvio Pdrao do preço dos jogadores por posição:")
print(variabilidade_preco)

#%%
"""
4. Distribuições (Histrograma, Assimetria)

a) Como se distribuem os gols por jogador? A distribuição é simétrica ou enviesada?
R: A distribuição dos gols por jogador é simétrica. 7.35

b) Existe uma concentração de pontuações em torno de zero (indicando rodadas ruins)?
R: Sim

c) O preço dos jogadores segue uma distribuição próxima da normal?
R: Sim

"""
#1
plt.figure(figsize=(8, 5))
sns.histplot(df['G'], bins=df['G'].max() + 1, kde=False, color='skyblue')
plt.title('Distribuição de Gols (G) por Registro de Rodada')
plt.xlabel('Número de Gols')
plt.ylabel('Frequência de Registros')
plt.show()

assimetria_g = df['G'].skew()
print(f"Assimetria (Skewness) dos Gols: {assimetria_g:.2f}\n")

#2
plt.figure(figsize=(10, 6))
sns.histplot(df['pontos_num'], bins=30, kde=True, color='green')
plt.title('Distribuição da Pontuação dos Jogadores por Rodada')
plt.xlabel('Pontuação (pontos_num)')
plt.ylabel('Frequência')
plt.show()
print(f"Assimetria (Skewness) da Pontuação: {assimetria_g:.2f}\n")

#3
plt.figure(figsize=(10, 6))
sns.histplot(df['preco_num'], bins=30, kde=True, color='orange')
plt.title('Distribuição do Preço dos Jogadores')
plt.xlabel('Preço (C$)')
plt.ylabel('Frequência')
plt.show()

assimetria_preco = df['preco_num'].skew()
print(f"Assimetria (Skewness) do Preço: {assimetria_preco:.2f}")

#%%
"""
5. Relações entre Variáveis (Correlação)

a) Qual a correlação entre preço do jogador e pontuação?
R: É de 0.37

b) Jogadores que fazem mais gols também dão mais assistências?
R: Não, a correlação é baixa porém positiva pois é raro isso acontecer

c) Existe relação entre número de faltas cometidas (FC) e cartões recebidos (CA, CV)?
R: Sim, mais faltas aumentam a chance de receber um cartão
"""

#1
correlacao_preco_pontos = df['preco_num'].corr(df['pontos_num'])
print(f"Correlação entre preço e pontuação: {correlacao_preco_pontos:.2f}")

#2
correlacao_gols_assistencias = df['G'].corr(df['A'])
print(f"Correlação entre Gols e assistências: {correlacao_gols_assistencias:.2f}")

#3
correlacao_fc_ca = df['FC'].corr(df['CA'])
correlacao_fc_cv = df['FC'].corr(df['CV'])

print(f"Correlação entre Faltas Cometidas (FC) e Cartão Amarelo (CA): {correlacao_fc_ca:.2f}")
print(f"Correlação entre Faltas Cometidas (FC) e Cartão Vermelho (CV): {correlacao_fc_cv:.2f}")

#%%
"""
6. Segmentações (Agrupamentos)
a) Quais clubes tiveram a maior média de pontos por jogador?
R: Corinthians e São Paulo

b) Quais posições mais contribuíram em roubadas de bola (RB)?
R: Lateral e meio
    lat    0.448495
    mei    0.444108

c)Qual rodada foi a mais produtiva em gols?
R: A rodada mais produtiva em gols foi a Rodada 27, com um total de 55 gols.
"""

#1
media_pontos_por_clube = df.groupby('clube')['pontos_num'].mean().sort_values(ascending=False).head(5)
print("TopClubes com maior média de pontos por jogador:")
print(media_pontos_por_clube)


#2
media_rb_por_posicao = df.groupby('posicao')['RB'].mean().sort_values(ascending=False)
print("Média (RB) por Posição:")
print(media_rb_por_posicao)

#3
gols_por_rodada = df.groupby('rodada_id')['G'].sum().sort_values(ascending=False)
rodada_mais_produtiva = gols_por_rodada.index[0]
print(f"A rodada mais produtiva em gols foi a Rodada {rodada_mais_produtiva}, com um total de {gols_por_rodada.iloc[0]} gols.")

#%%
"""
7. Outliers (Análise de Extremos)

a) Houve jogadores que fizeram pontuações extremamente altas em uma rodada específica?
R: Sim, Willian	do Cruzeiro	era um ata com 32.7 pontos na rodada 37

b) O preço de algum jogador destoou demais da sua pontuação real?
R: Sim, Zé Roberto	Palmeiras	custando 26.43 com 0 pontos

c) Existem goleiros com desempenho fora do esperado em defesas (DD, DP)?
R: Sim

"""

from scipy.stats import zscore

df['zscore_pontos'] = zscore(df['pontos_num'])
outliers_pontos = df[df['zscore_pontos'].abs() > 3].sort_values(by='pontos_num', ascending=False)

print(f"Registros de Outliers de Pontuação (Z-score > 3, ou seja, pontuações 'extremamente altas'): {outliers_pontos.shape[0]} registros")
display(outliers_pontos[['rodada_id', 'apelido', 'clube', 'posicao', 'pontos_num']].head())

#2

# Calculando o limite superior para 'caro'
Q1_preco = df['preco_num'].quantile(0.25)
Q3_preco = df['preco_num'].quantile(0.75)
IQR_preco = Q3_preco - Q1_preco
limite_outlier_preco = Q3_preco + 1.5 * IQR_preco

# Jogadores caros e com pontuação muito baixa (<= 1.0)
destoantes = df[(df['preco_num'] > limite_outlier_preco) & (df['pontos_num'] <= 1.0)]

print(f"Jogadores Outliers (Caros e Pontuação Baixa) em {destoantes.shape[0]} registros:")
display(destoantes[['rodada_id', 'apelido', 'clube', 'preco_num', 'pontos_num']].head())

#3

df_goleiros = df[df['posicao'] == 'gol']

# Análise de Outliers em Defesas Difíceis (DD) para goleiros
Q3_dd = df_goleiros['DD'].quantile(0.75)
IQR_dd = Q3_dd - df_goleiros['DD'].quantile(0.25)
limite_outlier_dd = Q3_dd + 1.5 * IQR_dd

outliers_goleiro_dd = df_goleiros[df_goleiros['DD'] > limite_outlier_dd].sort_values(by='DD', ascending=False)

print(f"Goleiros com Outliers em DD (Defesas Difíceis) em {outliers_goleiro_dd.shape[0]} registros:")
display(outliers_goleiro_dd[['rodada_id', 'apelido', 'clube', 'DD', 'pontos_num']].head())

#%%
"""
8. Visualização e Storytelling (Gráficos)

a) Como a pontuação varia por posição em um boxplot?
R: Ata, gol e mei são mais altos, nesse caso o ata seria a mediana

b) Qual o padrão de correlação mais forte entre as variáveis?
R: Seria os pontos_num (número de pontos) e G (gols)

c) Qual clube se destaca quando cruzamos gols x assistências?
R: Palmeiras

"""

plt.figure(figsize=(12, 6))
sns.boxplot(x='posicao', y='pontos_num', data=df)
plt.title('Variação da Pontuação por Posição')
plt.xlabel('Posição')
plt.ylabel('Pontuação (pontos_num)')
plt.grid(axis='y', alpha=0.5)
plt.show()


#2
scouts_cols = ['pontos_num', 'preco_num', 'G', 'A', 'RB', 'FC', 'CA', 'CV', 'SG']
corr_matrix = df[scouts_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Heatmap de Correlação das Métricas-Chave')
plt.show()

#3
gols_assist_clube = df.groupby('clube')[['G', 'A']].sum().reset_index()

plt.figure(figsize=(12, 8))
sns.scatterplot(x='G', y='A', data=gols_assist_clube, size='G', sizes=(50, 500), hue='clube', legend=False)
for i in range(gols_assist_clube.shape[0]):
    plt.text(x=gols_assist_clube['G'].iloc[i]+0.5, y=gols_assist_clube['A'].iloc[i],
             s=gols_assist_clube['clube'].iloc[i], fontdict={'size':9, 'weight':'bold'})
plt.title('Total de Gols vs Total de Assistências por Clube (Temporada)')
plt.xlabel('Total de Gols (G)')
plt.ylabel('Total de Assistências (A)')
plt.show()

#%%
"""
9. Síntese e Interpretação (Relatório Final)

a) Quais foram os maiores destaques individuais e coletivos da temporada?
R: Marcelo Lomba	Ponte Preta, Danilo Fernandes	Sport, Jadson	Corinthians, Cássio	Corinthians, Luan	Grêmio
R: Coletivos: São Paulo, Palmeiras, Corinhthians, Sport, Atlético-MG e Santos

b) O preço reflete de fato o desempenho dos jogadores?
R: Sim, de forma geral os jogadores mais caros tendem a pontuar mais

c) Que métricas são mais relevantes para diferenciar jogadores bons de medianos?
R: Os que tem  alta média e baixo desvio-padrão em seus "atributos" e pontos.
jogadores com alta média e alto desvio-padrão são mais arriscados

"""